import type { InkToolId } from '../ink/types';

export type MoodId =
  | 'serene'
  | 'dreamlike'
  | 'melancholic'
  | 'euphoric'
  | 'menacing'
  | 'cosmic'
  | 'playful'
  | 'sacred'
  | 'feral'
  | 'industrial';

export interface MoodPreset {
  id: MoodId;
  label: string;
  /** One line of art direction that opens the world. */
  lead: string;
  /** Words that carry the mood into every later direction. */
  tail: string;
  /** Ink colours the engine reaches for while this mood is set. */
  palette: string[];
  /** 0 = still, 1 = agitated. Shapes how much movement a beat asks for. */
  energy: number;
  /** Sound direction used when the score is generated by the model. */
  soundBrief: string;
  /** Tools that suit the mood. */
  tools: InkToolId[];
}

const ALL_TOOLS: InkToolId[] = ['drop', 'splatter', 'streak', 'curve', 'pool', 'drag', 'spray', 'backrun'];

export const MOODS: Record<MoodId, MoodPreset> = {
  serene: {
    id: 'serene',
    label: 'Serene',
    lead: 'A quiet, weightless film in pale mineral pigment and morning light. Slow, generous, unhurried.',
    tail: 'keep it calm, spacious and gently moving; nothing hurries',
    palette: ['#2f4f4a', '#5d8580', '#a8c4bd'],
    energy: 0.2,
    soundBrief: 'a single sustained tone, soft wind, distant water, no percussion',
    tools: ['pool', 'curve', 'drop', 'backrun'],
  },
  dreamlike: {
    id: 'dreamlike',
    label: 'Dreamlike',
    lead: 'An oneiric film where scale keeps slipping and soft focus blooms, as if remembered rather than seen.',
    tail: 'let scale and focus drift; nothing is quite solid',
    palette: ['#3a2f6b', '#6f5aa8', '#c3b6e8'],
    energy: 0.35,
    soundBrief: 'reversed reverb tails, soft choir hum, muffled heartbeat',
    tools: ['pool', 'curve', 'splatter', 'drag'],
  },
  melancholic: {
    id: 'melancholic',
    label: 'Melancholic',
    lead: 'A slow elegiac film in sepia and bruised blue, lit by a sun that has already gone down.',
    tail: 'hold the ache; let things linger and fade rather than resolve',
    palette: ['#3b2a1e', '#5a4632', '#26406b'],
    energy: 0.25,
    soundBrief: 'a lone cello line, rain on glass, room tone with a low hum',
    tools: ['curve', 'drag', 'pool', 'backrun'],
  },
  euphoric: {
    id: 'euphoric',
    label: 'Euphoric',
    lead: 'A bursting, over-saturated film that keeps finding new light sources to fall in love with.',
    tail: 'keep the energy rising and the colour hot',
    palette: ['#c25a2a', '#e8a020', '#c46a7d'],
    energy: 0.85,
    soundBrief: 'bright arpeggios, wide shimmering pad, a kick that keeps pushing forward',
    tools: ['splatter', 'spray', 'streak', 'drop'],
  },
  menacing: {
    id: 'menacing',
    label: 'Menacing',
    lead: 'A heavy, low-slung film with hard shadows, cold steel and something enormous just out of frame.',
    tail: 'keep a threat under everything; never let it resolve',
    palette: ['#141821', '#2b2b33', '#5b1d18'],
    energy: 0.45,
    soundBrief: 'sub-bass pressure, metal groans, a distant impact every few seconds',
    tools: ['splatter', 'drag', 'streak', 'backrun'],
  },
  cosmic: {
    id: 'cosmic',
    label: 'Cosmic',
    lead: 'A film at planetary scale: dust clouds, filament structures, light that took a long time to arrive.',
    tail: 'keep the sense of enormous distance and slow, inevitable motion',
    palette: ['#101a3a', '#3d5a8a', '#8f7fd8'],
    energy: 0.3,
    soundBrief: 'deep drones, sparse metallic pings, a vast empty room',
    tools: ['pool', 'spray', 'splatter', 'curve'],
  },
  playful: {
    id: 'playful',
    label: 'Playful',
    lead: 'A light, bouncy film that treats every shape as a character with somewhere to be.',
    tail: 'keep it springy and good-humoured; let shapes interact',
    palette: ['#e8a020', '#1d6b52', '#c0552a'],
    energy: 0.75,
    soundBrief: 'pizzicato strings, wooden clicks, a jaunty bass line',
    tools: ['drop', 'splatter', 'streak', 'spray'],
  },
  sacred: {
    id: 'sacred',
    label: 'Sacred',
    lead: 'A reverent film of gold leaf, incense smoke and shafts of light through high windows.',
    tail: 'keep it slow and ceremonial, as if something is being witnessed',
    palette: ['#6b4a12', '#9c7320', '#c9a154'],
    energy: 0.2,
    soundBrief: 'a struck bowl, low chant, air moving through stone',
    tools: ['pool', 'curve', 'backrun', 'drop'],
  },
  feral: {
    id: 'feral',
    label: 'Feral',
    lead: 'A wet, organic film of tendon, membrane and growth; beautiful and slightly wrong.',
    tail: 'keep it visceral and alive; let it grow toward the camera',
    palette: ['#5c1f33', '#8c2f1f', '#123f38'],
    energy: 0.6,
    soundBrief: 'wet clicks, breathing, a low organic pulse',
    tools: ['drag', 'splatter', 'curve', 'backrun'],
  },
  industrial: {
    id: 'industrial',
    label: 'Industrial',
    lead: 'A film of concrete, oxidised metal and sodium light, shot through with machinery rhythm.',
    tail: 'keep the rhythm mechanical and the surfaces hard',
    palette: ['#2d2d33', '#5a5a63', '#c0552a'],
    energy: 0.65,
    soundBrief: 'piston rhythm, electrical hum, grit underfoot',
    tools: ['streak', 'spray', 'splatter', 'drag'],
  },
};

export const MOOD_IDS = Object.keys(MOODS) as MoodId[];
export const DEFAULT_MOOD_ID: MoodId = 'dreamlike';

export function moodById(id: string | undefined): MoodPreset {
  return (id && MOODS[id as MoodId]) || MOODS[DEFAULT_MOOD_ID];
}

export const ALL_INK_TOOLS = ALL_TOOLS;
